name: open-amp lib Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  checkpatch_review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run checkpatch review
      uses: webispy/checkpatch-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        # checkout code before linting
        uses: actions/checkout@v2
        with:
          # fetch 20 commits (increase it if needed)
          fetch-depth: '20'
      - name: Lint
        run: |
          sudo apt-get update && sudo apt-get install gitlint
          gitlint
        # run linter (use latest version here)
        #uses: g4s8/gitlint-action@0.2
        #with:
          # see `inputs` section for more details
          #since: "2020-03-30"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
